### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by ariejan** [nickgartmann/boot2docker-status#4]
I'm new to docker, and it's not clear what this app does. It shows me a nice docker icon, sometimes with yellow dot. What happens when I click? Huh? 

It should be pretty straight forward to update the README to explain the workings of this app.

Thanks!

**Comment by nickgartmann** [comment]
Fixed in 1606e8c247f0a589dfcb9c5ac2359d6f23a920e5 if you have any other specific suggestions, add them to this issue and I'll consider them.
