### ISSUE TITLE
Auto-Update Functionality

### ISSUE THREAD

**Issue by brandongalbraith** [nickgartmann/boot2docker-status#6]
Would it be possible to include auto-update functionality using [Sparkle](http://sparkle-project.org/)?

**Comment by nickgartmann** [comment]
I'll look into it, thanks for the suggestion

**Comment by brandongalbraith** [comment]
I'm happy to do the legwork as well.

**Comment by nickgartmann** [comment]
@brandongalbraith a PR for it would make it much easier to include :)

**Comment by brandongalbraith** [comment]
Added to my TODO list :+1:

**Comment by brandongalbraith** [comment]
@nickgartmann Looks like Sparkle requires you have an Apple Developer account to perform signing. Have one? I don't, and if you don't either I'll just close this issue for now.
