### ISSUE TITLE
Quit?

### ISSUE THREAD

**Issue by gavinlaking** [nickgartmann/boot2docker-status#7]
Is there anyway to quit the app?

If I left/right click the icon on the menu bar it attempts to start/restart/stop boot2docker.

I can quit using a PID and `kill`, but an option might be nice.

**Comment by nickgartmann** [comment]
@gavinlaking you'll need to cmd+click the icon to reach the menu. Working on a better solution for that.

**Comment by gavinlaking** [comment]
Aha! Thanks :-)
